### ISSUE TITLE
PerformanceCounters are still registered even if Metrics.CompletelyDisableMetrics is set to True

### ISSUE THREAD

**Issue by behaug** [Recognos/Metrics.NET#10]
We have seen in some cases that registering performance counters can hang the process. (See https://ayende.com/blog/165217/performance-counters-sucks).

When I disable Metrics I would expect it to not even register these but it still does.

**Comment by PaulParau** [comment]
Thanks for pointing this out & linking that blog post.

We'll get back to you once we get a chance to look at the problem in more detail.

**Comment by nathvi** [comment]
...

**Comment by Liwoj** [comment]
Counters API sucks. Its better to not use it at all. 
Just remove `.WithAllCounters()` from configuration...

**Comment by PaulParau** [comment]
I fixed this in the latest prerelease build [v.0.4.5-pre](https://www.nuget.org/packages/Metrics.NET/0.4.5-pre). I've also added a warning in the xml documentation & removed `.WithAllCounters()` from the samples.

**Comment by PaulParau** [comment]
Fix released in the latest stable version [v0.4.7](https://www.nuget.org/packages/Metrics.NET/0.4.7)
