### ISSUE TITLE
Supporting Rolling Index for Elastic Reports

### ISSUE THREAD

**Issue by AmirSasson** [Recognos/Metrics.NET#11]
our IT guy requested to have a daily index when reporting to elastic as TTL is about to die according to Elastic latest news.
Daily Index can provide easy maintenance tool by deleting Index Daily.
Index name can be NAME-yyyy-MM-dd (i.e myindex-2016-04-17)

**Comment by AmirSasson** [comment]
I have submitted a pull request #12 that supports rolling index.
it supports backward compatibility,

**Comment by PaulParau** [comment]
Since the pull request was merged & a new version released, I'm closing this issue.
