### ISSUE TITLE
can`t release memory after completelyDisableMetrics

### ISSUE THREAD

**Issue by ycx2014** [Recognos/Metrics.NET#17]
Because class 'HistogramMetric' doesn't implement Interface 'IDisposable' ,so disable a metricContext can not disable histogram, class 'HistogramMetric' have a field reservoir,if the reservoirs type is 'ExponentiallyDecayingReservoir', the memory will cant be release.

**Comment by Liwoj** [comment]
Not true imho. 
Call to MetricsContext.CompletelyDisableMetrics will clear all repositories -> HistogramMetric instances are not referenced anywhere are will be garbage collected together with its reservoir. IDisposable is not needed most of the time in .NET unless you dealing with unmanaged resources....

**Comment by hinteadan** [comment]
Agreed with @Liwoj. Will close this.

**Comment by ycx2014** [comment]
@Liwoj  https://github.com/etishor/Metrics.NET/pull/124
