### ISSUE TITLE
ASP.NET Core Adapter 

### ISSUE THREAD

**Issue by alhardy** [Recognos/Metrics.NET#22]
I've added an alpha implementation to integrate Metrics.NET with ASP.NET Core middleware

https://github.com/alhardy/aspnet-metrics/blob/master/README.md

https://www.nuget.org/packages/AspNet.Metrics/

**Comment by AmirSasson** [comment]
Looks super useful !

**Comment by alhardy** [comment]
I've added a link to the ASP.NET Core adapter on the wiki. It's been upgraded to ASP.NET Core RC2
