### ISSUE TITLE
Is there a way to just provide a url path for the http endpoint?

### ISSUE THREAD

**Issue by orlandow** [Recognos/Metrics.NET#28]
From https://github.com/Recognos/Metrics.NET/wiki/Http-Endpoint-with-Charting-App

> Metric.Config.WithHttpEndpoint("http://localhost:1234/");

I want to have the charting app running on my hosted environment as well, not just localhost. I have several environments and managing the server names between them is a pain.

I'd like to be able to do:

`Metric.Config.WithHttpEndpoint("/metrics");`

and have it hosted at `http://whateveryourserveris/metrics`.

Is there a way to do that?

**Comment by orlandow** [comment]
I see you are using a regex to match the provided url:

[MetricsHttpListener.cs#L89](https://github.com/Recognos/Metrics.NET/blob/master/Src/Metrics/Visualization/MetricsHttpListener.cs#L89)

```c#
        private static string ParsePrefixPath(string listenerUriPrefix)
        {
            var match = Regex.Match(listenerUriPrefix, @"http://(?:[^/]*)(?:\:\d+)?/(.*)");
            return match.Success ? match.Groups[1].Value.ToLowerInvariant() : string.Empty;
        }
```

and later using that prefix to perform a substring on the incoming request.

```c#
 var urlPath = context.Request.RawUrl.Substring(this.prefixPath.Length)
                .ToLowerInvariant();

 switch (urlPath)
 {
      case "/":
```

I guess you could check if the `prefixPath` length is zero and strip the server part from the incoming request...

Does that make sense?

**Comment by Liwoj** [comment]
In hosted environment, using WithHttpEndpoint (uses HttpListener in the background) doesn't make much sense imho. Take a look at [OWIN Adapter](https://github.com/Recognos/Metrics.NET/wiki/OWIN-Metrics-Adapter). I'm using it in ASP.NET MVC app hosted in IIS and it works like a charm...

**Comment by orlandow** [comment]
Thanks, I'll check that out.
