### ISSUE TITLE
Change default context name

### ISSUE THREAD

**Issue by hedrie** [Recognos/Metrics.NET#29]
Is there a way to change the default context name? 
Right now, I configured metrics.net to report to graphite using [hostedgraphite](https://www.hostedgraphite.com/) as the host. It has the precondition that all the sent metrics must have a prefix with my app API_KEY (a guid). 
Metrics.net is always prefixing `[HOST.APP_NAME]`. I would like it can be `API_KEY.[HOST.APP_NAME]`. I also need API_KEY to be prefixed without the brackets `[]`.

**Comment by Paccc** [comment]
You can set an Environment variable or an appSettings key of `Metrics.GlobalContextName` with the context name that you want. It tries to read these variables on startup when setting the global context name. If neither are set then it defaults to the context name that you see.
