### ISSUE TITLE
FlotWebApp support for OWin endpoint changes

### ISSUE THREAD

**Issue by Greybird** [Recognos/Metrics.NET#3]
Hi,

While OWin.Metrics lets you change the endpoints for publishing health and metrics' json, the FlotWebApp has hard-coded /json and /health paths in its html resource.

Do you have plans to allow customiing the webapp with endpoints override ?

Regards,

**Comment by hinteadan** [comment]
Well... do you have a real use case for this?

Because the reasoning here is that if you customize the endpoints you probably want to do so in order to consume them from some other custom application, therefore being irrelevant if the FlotViewApp works or not since it wouldn't be used.

This being the assumption, we have no plans for this feature, but please detail your scenario and let's see if it would make sense.

Thanks,
Dan.

**Comment by Greybird** [comment]
Hi,

Thanks for you interest in my issue!

I have a real use case, but I'd be glad to hear your views on it.

I'm using Metrics.NET on a Web API service.
I am exposing data on /service/v1/...

While the default for health, ping, and the web app would be ok (/service/v1/health, /service/v1/ping, /service/v1/metrics), I'm not conortable with /service/v1/json for the metrics json exposition, as it fails to convey the nature of the data.

That's why I redirected /json to /metrics/json and at the same time, /metrics to /metrics/ui.
Then I found that the WebApp was not able to access metrics data.

On the usage part, we'll plugf some monitoring systems (either from our team or client teams), and also would like to use these to help diagnose issues either on support team or dev team.

Regards,

Arnaud

**Comment by hinteadan** [comment]
Hi, I think your scenario would be covered with the existing functionality, using the following config:
```c#
Metric.Config
    .WithAllCounters()
    .WithOwin(middleware => app.Use(middleware), config => config
        .WithRequestMetricsConfig(c => c.WithAllOwinMetrics())
        .WithMetricsEndpoint(cfg => cfg
            .MetricsEndpoint("metrics/ui")
            .MetricsJsonEndpoint("metrics/json")
            .MetricsHealthEndpoint("metrics/health")
        )
    );
```

and also having a "public" endpoint for the metrics' json _(if needed)_, defined in a specific WebAPI controller which redirects to the _metrics/json_ endpoint:

```c#
public class PublicMetricsController : ApiController
    {
        public IHttpActionResult Get()
        {
            return Redirect(Request.RequestUri.AbsoluteUri + "/../metrics/json");
        }
    }
```
With this we have:
- All the Metrics related stuff under: **_\[root\]/metrics/\[etc.\]_**
- Your Service endpoints under: **_\[root\]/\[endpoints\]_**

Here is an attachment with a working solution for this config: 
[MetricsWebApiPlayground.zip](https://github.com/Recognos/Metrics.NET/files/195434/MetricsWebApiPlayground.zip)

Would this do? Does it cover your needs, or have I misunderstood something?

Dan.

**Comment by Greybird** [comment]
Hi,

Actually, the root /json is bothering me, so I don't want/need this redirect.

But in fact you are right, if I keep the web app with health and json at same relative path, it works, so in my case it is perfect, I will make everything go under /metrics rather than root.

Probably not that important to allow full configuration for other cases.

Thanks for your response!

Arnaud
