### ISSUE TITLE
TimerMetric doesn't mark userValue in 'meter'

### ISSUE THREAD

**Issue by epeshk** [Recognos/Metrics.NET#33]
https://github.com/Recognos/Metrics.NET/blob/master/Src/Metrics/Core/TimerMetric.cs (47)

Possible bug
Timer mark userValue in 'histogram', but not in 'meter', and meter values can't be splitted by userValue's

(47) line should be:
`                this.meter.Mark(userValue);`

Pull request to fix it: #34

**Comment by PaulParau** [comment]
Good catch! The PR was merged & new version released.
