### ISSUE TITLE
Error handling in the reporting timer

### ISSUE THREAD

**Issue by maxcherednik** [Recognos/Metrics.NET#39]
Once there is an exception during metrics reporting—csv file was locked, elastic search wasn't reachable and so on, I would rather skip this reporting point and had the next one. What we have at the moment — it stops forever.

**Comment by PaulParau** [comment]
Hi,

In the latest version ([v.0.4.6-pre](https://www.nuget.org/packages/Metrics.NET/0.4.6-pre)) you can configure the tolerance to failure of reporters through a config key. You can leave the behavior as it is now (it's the default option), specify unlimited tolerance to failures (it will baiscally never stop trying to report) or you can configure a certain number of consecutive errors to tolerate. It's all documented [here](https://github.com/Recognos/Metrics.NET/wiki/Configuration).

**Comment by PaulParau** [comment]
Fix released in the latest stable version [v0.4.7](https://www.nuget.org/packages/Metrics.NET/0.4.7)
