### ISSUE TITLE
Generated CSV File Name isn't correct. You guys need to remove spaces.

### ISSUE THREAD

**Issue by nathvi** [Recognos/Metrics.NET#42]
[ComputerName.ConsoleApplication17_vshost - Application] ConsoleApplication17.vshost Uptime Seconds.Gauge

^ This is the name of the file that is generated for Excel to read. 

It needs to be in this format.
[ComputerName.ConsoleApplication17_vshost - Application] ConsoleApplication17.vshost UptimeSeconds.Gauge

**Comment by PaulParau** [comment]
Hi,
Sorry it took so long to respond. Could you please clarify why the current behavior is wrong? If you named your metric "Uptime Seconds" then that is what is going to appear in the name of the CSV file, or am I misunderstanding your question?
