### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by aazizorg** [Recognos/Metrics.NET#43]
The project this is forked from has an issue (https://github.com/etishor/Metrics.NET/issues/133) about .NET Core support, but it seems to have been untouched for most of this year and this fork being more up to date.

Is there any plans to add a .NET Core build to Metrics.NET?

**Comment by Reonekot** [comment]
Two issues Down #32 
https://github.com/Recognos/Metrics.NET/issues/32
