### ISSUE TITLE
Server farm aggregation support

### ISSUE THREAD

**Issue by Andrei-Rinea** [Recognos/Metrics.NET#44]
Is there some adapter or recommendation / best practice for aggregating metrics in a server farm?

For example I have a project that runs on 4 servers and I would like aggregated metrics for the whole farm besides the local metrics. Any idea on this?

Thanks!

**Comment by PaulParau** [comment]
Hi Andrei,

I think the best solution would be to report metrics from each of the machines to a centralized location (e.g. reporting to Graphite / some other db) and dealing with aggregation at that centralized level. You can have a look at a list of reporters [here](https://github.com/Recognos/Metrics.NET/wiki/Metrics-Reporting) and you can also write your own reporter if you so choose.

As a side note, a Metrics.NET instance supports pulling data from other instances, but I'm not sure if this is what you're looking for: by using the `.RegisterRemote` extension method for `MetricsConfig`, a remote metrics context is attached which periodically pulls JSON data from a specified URL. The remote context is however added as a child context, so the metrics of each machine will not be explicitly aggregated (i.e. summed) and will be recorded separately. So, depending on what level of aggregation you're looking for, this might not be enough.

**Comment by PaulParau** [comment]
Hi, I'm closing this issue. If you have any other questions, feel free to ask!
