### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by peske** [Recognos/Metrics.NET#5]
First, of course, congs for the great work! It's really great library.

But second I must criticise your "Release" policy. Current release is 2.16 (more than year old), and prerelease already reached 3.4! It is not a good practice - it is more like "I won't bother with release anymore..." I strongly suggest slowing down with new features and stabilize one release version.

One may say that there's actually no difference, but there is. If nothing more all the assemblies that are implementing Metrics.NET also cannot be published as "release" as long as they are referencing some prerelease package (i.e. Metrics.NET).

So again, no doubt that you are doing a great job, but if possible please try to do it more in "by-the-book" fashion.

Sorry for criticism and thanks!

**Comment by LatisVlad** [comment]
Hi peske,

I totally agree with you on the "Release" policy. I don't know if you are aware, but last year an unfortunate event left this library without its owner. After some time and consideration, we(4 colleagues of etishor) decided to continue his great work. 
So for about a month now we have full access to this repo, and made this the "official" repo.

To conclude, be sure that we will do our best to do this "by-the-book", but bare with us, as we accommodate with the codebase, and become "confident" to create a release policy. 

Thanks for your understanding!
