### ISSUE TITLE
Content-Type reverted

### ISSUE THREAD

**Issue by glennular** [Recognos/Metrics.NET#51]
Went to get the newest nuget  and found that the fix for Content-Type is not in

747a89d25e1ee78532c696f9ee339d641ad1b60d

See https://github.com/Recognos/Metrics.NET/blob/master/Src/Adapters/Owin.Metrics/Middleware/MetricsEndpointMiddleware.cs#L98

Can you resolve @PaulParau ?

**Comment by PaulParau** [comment]
No idea how that happened, probably some botched merge; I've fixed it in the latest nuget package.

**Comment by glennular** [comment]
Thanks.

Yea, I tried to follow the commit trail, but couldn't figure it out either
