### ISSUE TITLE
About fixing bug in Flot Visualisation

### ISSUE THREAD

**Issue by tsibelman** [Recognos/Metrics.NET#67]
We want to fix bug with visualization in metrics but we see that the all the code is inside https://github.com/etishor/Metrics.NET.FlotVisualization assembly

How can we give you a pull request ? I can fork above assembly and make a change and build and give you corrected Metrics.Endpoints.index.full.html.gz . Is it OK ? Or you would like some different way doing this ?

**Comment by PaulParau** [comment]
Hi,

I think the best way to do it is for us to clone it over here under the Recognos organization, as we have done with the other repos (we missed this one for some reason). I'm going to do it tomorrow, and then you can make a normal PR.

**Comment by PaulParau** [comment]
I've cloned the project [here](https://github.com/Recognos/Metrics.NET.FlotVisualization) so we can maintain this part of the library as well. Feel free to submit a PR with the bugfix.

**Comment by tsibelman** [comment]
Great, thank you very much.

**Comment by tsibelman** [comment]
My collegue had made a pull request there

**Comment by tsibelman** [comment]
Hi @PaulParau we saw you accepted the PR in other repository, when do you plan to integrate it into this repository ? Also we would like to have a version of metrics with this fix.

**Comment by PaulParau** [comment]
Hi, I'm currently having some trouble building the UI solution and this is in turn preventing me from updating the visualization app inside the main repository.

I don't know yet what the cause is, but I'll try more tomorrow.

**Comment by PaulParau** [comment]
@tsibelman I finally managed to build the UI solution. I've integrated the latest version of the visualization app in the dev branch, and released it as part of version 0.5.2-pre of Metrics.NET.

**Comment by tsibelman** [comment]
It great to here @PaulParau , thank you very much.  BTW what is your policy for moving prereleas to release ? Will you release 0.5.2 soon after 0.5.2-pre ? Or it could take a while ?

**Comment by PaulParau** [comment]
We usually wait a period of time (how long depends on how big the changes are) after releasing a prerelease version, so people get a chance to install the new version and report any issues.

In this case, I want to make sure that nothing went wrong with building & updating the UI, since it's the first time we did this in a while. I think a few days to a week should be enough, depending on the number of downloads.

Do you require a stable version as soon as possible?

**Comment by tsibelman** [comment]
We tested the 0.5.2-pre nuget looks like the ui do not contains the changes. Generally we would like to get stable version of nugets for our production deployments, so we would love to get it soon after the prerelease.

**Comment by PaulParau** [comment]
That is weird, I'm sure I added the new UI version. I'll check & get back.

**Comment by tsibelman** [comment]
Ok thank you.

**Comment by PaulParau** [comment]
I checked and the fix your colleague made gets removed by the build process (see [here](https://github.com/Recognos/Metrics.NET.FlotVisualization/issues/1). I did not check this before accepting the pull request so v0.5.2-pre does indeed not contain the fix. (good that I released it as prerelease :) ).
