### ISSUE TITLE
Owin adapter return wrong content-type

### ISSUE THREAD

**Issue by x00n** [Recognos/Metrics.NET#69]
Hi all,

I would like to add metrics to my owin based application. I used the code snippet on the owin adapter page and referenced the two assemblies from nuget. Everything works fine but the dashboard. In fact when I connect to the dashboard the browser shows not the render of the response HTML but the HTML itself, also in the browser console there is a message saying that the returned type is Json but the content looks like to be a document.

I had a look to my middlewares to check if one of them could interfere with the response but it's not the case. 

Could you please help me?

Thanks in advance
Federico

**Comment by PaulParau** [comment]
Hello,

There was indeed a bug with the content-type of the web app (it was mistakenly set to application/json instead of text/html - see issue #77 ).
It was fixed in the most recent version of the owin adapter.
