### ISSUE TITLE
Prometheus report

### ISSUE THREAD

**Issue by rokka** [Recognos/Metrics.NET#7]
Hi,

I just found this cool project. And I would like to use it in combination with Prometheus (http://prometheus.io/), an active monitoring system.

Are you interested that I add an an prometheus report to your project, which listens on "/metrics" and returns prometheus readable output?

Greetings
Andre

**Comment by hinteadan** [comment]
Hi,

I think the best approach for these custom reporters is to keep them separate from the core, I had a similar issue when  I wrote a Google Analytics Reporter.

So, please make a separate git repo for it and publish it on its own, separate NuGet Package.

Here is my solution for the Google Analytics Reporter. Yours' should have a similar infrastructure, but storing implementation for Prometheus.io:
GitHub: https://github.com/hinteadan/Metrics.NET.GAReporting
NuGet: https://www.nuget.org/packages/Metrics.Reporters.GoogleAnalytics/1.0.14-pre

- Dan H.

**Comment by LatisVlad** [comment]
Hi, 
I agree with Dan on this.
Please keep us in touch with this :)
Thanks,
Vlad
