### ISSUE TITLE
Owin adapter returns wrong content type for flot web app

### ISSUE THREAD

**Issue by orenht** [Recognos/Metrics.NET#77]
In the class MetricsEndpointMiddleware, the content type returned for the flot app is application/json, when it needs to be text/html I believe.

This was not discovered until now, because there was another bug in the content type header(it was sent as ContentType, without the '-'). So it defaulted to html, and everything worked.

I'd love for a quick fix for this one, and uploading to NuGet.
Thanks

**Comment by PaulParau** [comment]
Hey, thanks for pointing this out! A classic case of one bug cancelling out another :)

I've fixed it and released version 0.5.4 of the [Owin.Metrics](https://www.nuget.org/packages/Owin.Metrics/) package.

**Comment by orenht** [comment]
Great, thanks.
You can resolve this issue now :)

Also, can you please take a look at some other issues and pull requests? Thank you
